### ISSUE TITLE
Color Themes cannot be applied anymore

### ISSUE THREAD

**Issue by derveit** [didierverna/fixme#1]
Since the new Version 4.3 it is not possible anymore to apply the "color" theme.

> Error: File `fxtargetlayoutcolorcb.sty' not found. \fxusetargetlayout{colorcb}

Color Theme has definetly worked in the last version (the normal one, not the cb one). 
My LaTeX Packages are up to date.

This guy has the same problem: 
http://tex.stackexchange.com/questions/350502/error-file-fxthemecolor-sty-not-found-with-fixme-package

My MWE:

---------------

\documentclass[]{article}

\usepackage{luacode}
\usepackage{polyglossia}
\setdefaultlanguage[spelling=new, babelshorthands=true]{german}
\usepackage{xcolor}
\usepackage{blindtext}

\usepackage[%
  status=draft,
  layout=margin,
  %index=true,
  lang=ngerman,
  author=,			% no author
]{fixme}

%\fxusetargetlayout{plain} % Manual p.16 This one works
\fxusetargetlayout{colorcb} % This one doesn't

\begin{document}
  \blindtext[1] \fxnote{TEST}
  \blindtext[1] \fxwarning{TEST}
\end{document}

------------------------------------------

Would really appreciate an update since my thesis is full of fxnotes :-)

**Comment by didierverna** [comment]
See my answer on StackExchange. I think it's a MiKTeX problem. I'm leaving this open until you can confirm.

**Comment by didierverna** [comment]
I got confirmation that this is a MiKTeX bug, so I'm closing the issue.

**Comment by derveit** [comment]
Hey, 

ahhh I see. 

Didn't know this could happen with MikTex packages. 

Thank you very much for the quick response! 

Best regards, 

Veit 

Am 2017-02-01 12:09, schrieb Didier Verna: 

> I got confirmation that this is a MiKTeX bug, so I'm closing the issue. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/didierverna/fixme/issues/1#issuecomment-276631546
[2]
