### ISSUE TITLE
Exemples illustrés manquants dans la documentation

### ISSUE THREAD

**Issue by quark67** [didierverna/fixme#2]
Pourriez-vous ajouter des exemples illustrés montrant concrètement ce que donne l'usage de votre package ? Cela aiderait à voir si le package convient pour tel ou tel usage.

**Comment by didierverna** [comment]
Bonjour,

je ne suis pas sûr que cela apporte grand chose, mais j'imagine que je pourrais en effet ajouter un répertoire d'exemples afin d'illustrer tous les styles de notes. Merci pour la suggestion !
