### ISSUE TITLE
pdfsignote layout does not work

### ISSUE THREAD

**Issue by soerenwolfers** [didierverna/fixme#4]
The MWE 

    \documentclass[status=draft]{article}
    \usepackage{fixme}
    \fxsetup{layout=pdfsignote} 
    \begin{document}
    Test\fxnote{test}
    \end{document}

produces the error

    ! Undefined control sequence.
    <argument> \equal 
                      {\cmdfx@note@author }{}
    l.7 Test\fxnote{test}

I am not sure if there is a connection, but if I add `\usepackage[USenglish]{babel}` (which I had in my original document) I instead get

    ! Missing \endcsname inserted.
    <to be read again> 
                       \<let>-command 
    l.6 Test\fxnote{test}

Everything works fine, with or without `babel`, if I change the layout to `pdfnote`.

**Comment by didierverna** [comment]
Hello,

thanks for the report. This will be fixed in the upcoming 4.5 release (and sooner than that in the repo).
